### ISSUE TITLE
引用中嵌套代码块时的代码行距问题

### ISSUE THREAD

**Issue by Louvane** [sylviaxgj/typora-forest-theme#23]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/801f08c3-499d-4506-8c05-451e024d1010">

引用中的代码块行距太小
建议将`forest.css`中的`blockquote`的`line-height: 1;`去掉

```css
/* quote */
blockquote {
  position: relative;
  padding: 1rem;
  background-color: var(--quote-bg-color);
  border-radius: 6px;
  line-height: 1;
}
```

<img width="933" alt="image" src="https://github.com/user-attachments/assets/5ee8457e-9ca7-42ec-b3f2-2790ac90510c">
